services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
        
  river-ui:
    image: ghcr.io/riverqueue/riverui:latest
    network_mode: host
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - 8080:8080
