// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

type DocCampsite struct {
	ID      int32
	AssetID int32
	Status  string
	Name    string
	Region  string
	X       float64
	Y       float64
}

type DocHut struct {
	ID      int32
	AssetID int32
	Name    string
	Status  string
	Region  string
	X       float64
	Y       float64
}
